name: CICD

on:
  push:
    branches: [develop]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: grant privileges to gradlew
        run: chmod +x gradlew

      - name: run test
        run: ./gradlew test

      - name: run build
        run: ./gradlew clean build -x test

  CD:
    runs-on: ubuntu-latest
    needs: CI

    steps:
      - uses: actions/checkout@v2

      - name: use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: grant privileges to gradlew
        run: chmod +x gradlew

      - name: run build
        run: ./gradlew clean build -x test

      - name: create docker image
        run: docker build --tag camillia .

      - name: upload to docker hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 0816jinjin/camillia:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}